= AI Validation
Firstname Lastname <author@asciidoctor.org>
3.0, July 29, 2022: AsciiDoc article template
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Notes from preparing the AI validation.

== Idea

1. flash AI Accelerator validation firmware to env5 mcu
2. build a new hw accelerator
3. download the HW accelerator to env5
4. download input test data for the accelerator
5. run a prediction with the accelerator
6. print the result from env5 via serial

We want to reduce the need for having to rebuild and flash a new firmware for the mcu, when testing a new hw accelerator.

== Workflow

* create `NetworkConfiguration.c` in `src/` folder
* add your network credentials to `NetworkConfiguration.c` as follows
....
networkCredentials_t networkCredentials = {
    .ssid = "your_ssid",
    .password = "your_password"
};
....
* start the http server in `src/python/bitfile_http_server/bitfile_http_server.py`
* copy the url that was printed on the terminal in the previous step and add the following to `NetworkConfiguration.c`
....
char baseUrl[] = "your_url_from_bitfile_server";
....
* build and flash `AIValidation.c`
* build your HW Accelerator
* copy the file to `build_dir_output/output/env5_top_reconfig.bin`. If you use the the script in `src/vivado_build/autobuild_binfile_vivado2021.1.sh` the file should already be in the right place
* open a minicom with `minicom -b 115200 -o -D /path_to_your_tty`
* hit `h` to print the available commands
* use the menu to
** connect to wifi
** download the binfile
** predict


== REST Server
The server is used to provide the bitfile and input data for testing offers the following methods

* `/binfile/<position>`: download the part of the binfiile at position `<position>`
* `/binfile_length`: get the size of the binfile in bytes as a string
* `/data_to_compute`: download the input data for a prediction as a string. Different values are separated by `;`
* `/data_to_compute_length`: get the number of input data points as a string. E.g., if data has the form `"1;2;3"`, this method will return `"3"`.
* `/result_length`: get the number of values that will be produced by the prediction
