/*
 * This is an autogenerated stub. 
 * Do not change it manually. 
 */

#include "../middleware/middleware.h"
#include "Sleep.h"
#include "ai.h"

#include <stdint.h>
#include <stdbool.h>

#define ADDR_SKELETON_INPUTS 0
#define ADDR_COMPUTATION_ENABLE 100

static void modelCompute(bool enable);
static uint8_t get_id(void);

static uint64_t accelerator_id = 47;
static uint32_t accelerator_addr = 4000;

bool AI_deploy(void)
{
   middlewareInit();
   middlewareConfigureFpga(accelerator_addr);
   sleep_for_ms(200);
   bool is_deployed_successfully = (get_id() == accelerator_id);
   middlewareDeinit();
   return is_deployed_successfully;
}

int8_t AI_predict(int8_t *inputs)
{
   int8_t _result;

   middlewareInit();
   middlewareUserlogicEnable();
   middlewareWriteBlocking(ADDR_SKELETON_INPUTS+0, (uint8_t*)(inputs), 6);
   modelCompute(true);

   while( middlewareUserlogicGetBusyStatus() );
   modelCompute(false);
   for(int i = 0; i < 1; i++){
     middlewareReadBlocking(ADDR_SKELETON_INPUTS+0+i, (uint8_t *)(&_result)+i, 1);
     middlewareReadBlocking(ADDR_SKELETON_INPUTS+0+i, (uint8_t *)(&_result)+i, 1);
   }
   modelCompute(false);
   middlewareUserlogicDisable();
   middlewareDeinit();
   return _result;
}

static void modelCompute(bool enable)
{
   uint8_t cmd = (enable ? 1 : 0);
   middlewareWriteBlocking(ADDR_COMPUTATION_ENABLE, &cmd, 1);
}

static uint8_t get_id(void)
{
   middlewareUserlogicEnable();
   uint8_t id = middlewareGetDesignId();
   middlewareUserlogicDisable();
   return id;
}

