/*
 * This is an autogenerated stub. 
 * Do not change it manually. 
 */

#include "middleware.h"
#include "Sleep.h"
#include "AI.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define ADDR_COMPUTATION_ENABLE 0
#define ADDR_SKELETON_INPUTS 1


static void modelCompute(bool enable);
static uint8_t get_id(void);

bool AI_deploy(uint32_t accelerator_addr, uint64_t accelerator_id)
{
   middlewareInit();
   middlewareConfigureFpga(accelerator_addr);
   sleep_for_ms(200);
   bool is_deployed_successfully = (get_id() == accelerator_id);
   middlewareDeinit();
   return is_deployed_successfully;
}

void AI_predict(int8_t *inputs, size_t num_inputs, int8_t *result, size_t num_results)
{
   middlewareInit();
   middlewareUserlogicEnable();
   middlewareWriteBlocking(ADDR_SKELETON_INPUTS+0, (uint8_t*)(inputs), num_inputs);
   modelCompute(true);

   while( middlewareUserlogicGetBusyStatus() );
   modelCompute(false);
   for(int i = 0; i < num_results; i++){
       middlewareReadBlocking(ADDR_SKELETON_INPUTS+0+i, (uint8_t *)(&result)+i, 1);
       middlewareReadBlocking(ADDR_SKELETON_INPUTS+0+i, (uint8_t *)(&result)+i, 1);
   }
   modelCompute(false);
   middlewareUserlogicDisable();
   middlewareDeinit();
}

static void modelCompute(bool enable)
{
   uint8_t cmd = (enable ? 1 : 0);
   middlewareWriteBlocking(ADDR_COMPUTATION_ENABLE, &cmd, 1);
}

static uint8_t get_id(void)
{
   middlewareUserlogicEnable();
   uint8_t id = middlewareGetDesignId();
   middlewareUserlogicDisable();
   return id;
}

